# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import hab_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0005_auto_20171225_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingoccupantrequest',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upcomingoccupantrequest',
            name='idPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='id_pics', validators=[hab_app.models.UpcomingOccupantRequest.validate_image]),
        ),
        migrations.AddField(
            model_name='upcomingoccupantrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', validators=[hab_app.models.UpcomingOccupantRequest.validate_image]),
        ),
        migrations.AddField(
            model_name='upcomingoccupantrequest',
            name='saORda',
            field=models.CharField(choices=[('Specially/Differently Abled', 'Specially/Differently Abled'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='hostelName',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='upcomingoccupantrequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='upcomingoccupantrequest',
            name='To_be_approved_by',
        ),
        migrations.RemoveField(
            model_name='upcomingoccupantrequest',
            name='isApprovedFirst',
        ),
    ]
