# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0006_auto_20171226_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('jan_range', models.DateField()),
                ('january', models.BooleanField()),
                ('feb_range', models.DateField()),
                ('feburary', models.BooleanField()),
                ('mar_range', models.DateField()),
                ('march', models.BooleanField()),
                ('apr_range', models.DateField()),
                ('april', models.BooleanField()),
                ('may_range', models.DateField()),
                ('may', models.BooleanField()),
                ('jun_range', models.DateField()),
                ('june', models.BooleanField()),
                ('july_range', models.DateField()),
                ('july', models.BooleanField()),
                ('aug_range', models.DateField()),
                ('august', models.BooleanField()),
                ('sept_range', models.DateField()),
                ('september', models.BooleanField()),
                ('oct_range', models.DateField()),
                ('october', models.BooleanField()),
                ('nov_range', models.DateField()),
                ('november', models.BooleanField()),
                ('dec_range', models.DateField()),
                ('december', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Automation',
                'verbose_name': 'Automation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='automation',
            unique_together=set([('month', 'year')]),
        ),
    ]
