# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0008_auto_20180105_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='apr_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='aug_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='dec_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='feb_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='jan_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='july_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='jun_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='mar_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='may_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='nov_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='oct_range',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='sept_range',
            field=models.DateField(blank=True, null=True),
        ),
    ]
