# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0009_auto_20180106_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
