# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0010_auto_20180106_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='april',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='august',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='december',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='feburary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='january',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='july',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='june',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='march',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='may',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='november',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='october',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='september',
            field=models.BooleanField(default=False),
        ),
    ]
