# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0010_auto_20171224_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='catering',
            field=models.IntegerField(choices=[(0, 'Very Poor'), (1, 'Poor'), (2, 'Average'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='cleanliness',
            field=models.IntegerField(choices=[(0, 'Very Poor'), (1, 'Poor'), (2, 'Average'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_b',
            field=models.IntegerField(choices=[(0, 'Very Poor'), (1, 'Poor'), (2, 'Average'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_d',
            field=models.IntegerField(choices=[(0, 'Very Poor'), (1, 'Poor'), (2, 'Average'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_l',
            field=models.IntegerField(choices=[(0, 'Very Poor'), (1, 'Poor'), (2, 'Average'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='opi_value',
            field=models.FloatField(),
        ),
    ]
