# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0014_auto_20171231_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='month_year',
            field=models.CharField(default='12_2017', max_length=255),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='month_year',
            field=models.CharField(default='12_2017', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='preference',
            name='month_year',
            field=models.CharField(default='2_2018', max_length=255),
        ),
    ]
