# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0017_auto_20180106_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='h1',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='h2',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='h3',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255),
        ),
    ]
