# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0021_auto_20180107_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalpreference',
            options={},
        ),
    ]
