# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0022_auto_20180107_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalpreference',
            options={'verbose_name': 'FinalPreference', 'verbose_name_plural': 'FinalPreference'},
        ),
    ]
